services:
  mc_gtnh:
    image: glitchless/gli_mc_stoneblock:18
    restart: unless-stopped
    ports:
      - "25568:25565"
    volumes:
      - ./world:/minecraft/world
      - ./logs:/minecraft/logs